Bumped what4 dependency version to be at least 1.2. Refs #277.
what4 1.1 does not compile on ghc>=9 due to missing instances. Forcing this to
be at least 1.2 fixes this:

src/What4/Expr/App.hs:509:5: error:
    • No instance for (FoldableFC App)
        arising from a use of ‘traverseFC_’
    • In a stmt of a 'do' block:
        traverseFC_ (countOccurrences' visited) (appExprApp e)
      In the second argument of ‘($)’, namely
        ‘do traverseFC_ (countOccurrences' visited) (appExprApp e)’
      In a stmt of a 'do' block:
        incOccurrence visited idx
          $ do traverseFC_ (countOccurrences' visited) (appExprApp e)
    |
509 |     traverseFC_ (countOccurrences' visited) (appExprApp e)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/What4/Expr/App.hs:513:5: error:
    • No instance for (FoldableFC (NonceApp t))
        arising from a use of ‘traverseFC_’
    • In a stmt of a 'do' block:
        traverseFC_ (countOccurrences' visited) (nonceExprApp e)
      In the second argument of ‘($)’, namely
        ‘do traverseFC_ (countOccurrences' visited) (nonceExprApp e)’
      In a stmt of a 'do' block:
        incOccurrence visited idx
          $ do traverseFC_ (countOccurrences' visited) (nonceExprApp e)
    |
513 |     traverseFC_ (countOccurrences' visited) (nonceExprApp e)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/What4/Expr/App.hs:544:23: error:
    • No instance for (FoldableFC App) arising from a use of ‘toListFC’
    • In the first argument of ‘sequence’, namely
        ‘(toListFC (boundVars' visited) (appExprApp e))’
      In a stmt of a 'do' block:
        sums <- sequence (toListFC (boundVars' visited) (appExprApp e))
      In the second argument of ‘($)’, namely
        ‘do sums <- sequence (toListFC (boundVars' visited) (appExprApp e))
            return $ foldl' Set.union Set.empty sums’
    |
544 |     sums <- sequence (toListFC (boundVars' visited) (appExprApp e))
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/What4/Expr/App.hs:549:23: error:
    • No instance for (FoldableFC (NonceApp t))
        arising from a use of ‘toListFC’
    • In the first argument of ‘sequence’, namely
        ‘(toListFC (boundVars' visited) (nonceExprApp e))’
      In a stmt of a 'do' block:
        sums <- sequence (toListFC (boundVars' visited) (nonceExprApp e))
      In the second argument of ‘($)’, namely
        ‘do sums <- sequence
                      (toListFC (boundVars' visited) (nonceExprApp e))
            return $ foldl' Set.union Set.empty sums’
    |
549 |     sums <- sequence (toListFC (boundVars' visited) (nonceExprApp e))
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```